/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerProfile {
  'contactName' : string,
  'gstNumber' : string,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export interface InvoiceData {
  'customer' : CustomerProfile,
  'request' : QuoteRequest,
  'quotation' : Quotation,
}
export interface Order {
  'requestId' : bigint,
  'manufacturingNotes' : [] | [string],
  'deliveryTrackingInfo' : [] | [string],
  'finalPaid' : boolean,
  'advancePaid' : boolean,
  'customerId' : Principal,
}
export interface OrderUpdateArgs {
  'requestId' : bigint,
  'manufacturingNotes' : [] | [string],
  'deliveryTrackingInfo' : [] | [string],
}
export interface Quotation {
  'deliveryCharge' : number,
  'requestId' : bigint,
  'gstPercent' : number,
  'sentAt' : bigint,
  'notes' : [] | [string],
  'totalPrice' : number,
  'basePrice' : number,
  'validUntil' : bigint,
}
export interface QuotationArgs {
  'deliveryCharge' : number,
  'requestId' : bigint,
  'gstPercent' : number,
  'notes' : [] | [string],
  'basePrice' : number,
  'validUntil' : bigint,
}
export interface QuoteRequest {
  'id' : bigint,
  'height' : number,
  'status' : string,
  'createdAt' : bigint,
  'drawingFileId' : [] | [string],
  'deliveryLocation' : string,
  'boxType' : string,
  'length' : number,
  'quantity' : bigint,
  'customerId' : Principal,
  'width' : number,
  'adminNotes' : [] | [string],
  'material' : string,
}
export interface QuoteRequestArgs {
  'height' : number,
  'drawingFileId' : [] | [string],
  'deliveryLocation' : string,
  'boxType' : string,
  'length' : number,
  'quantity' : bigint,
  'width' : number,
  'material' : string,
}
export interface RegisterCustomerProfileArgs {
  'contactName' : string,
  'gstNumber' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveQuote' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<[Principal, CustomerProfile]>>,
  'getAllQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoiceData' : ActorMethod<[bigint], [] | [InvoiceData]>,
  'getMyProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getMyQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getQuotation' : ActorMethod<[bigint], [] | [Quotation]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAdvancePaid' : ActorMethod<[bigint], undefined>,
  'registerCustomerProfile' : ActorMethod<
    [RegisterCustomerProfileArgs],
    undefined
  >,
  'rejectQuote' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[CustomerProfile], undefined>,
  'sendQuotation' : ActorMethod<[QuotationArgs], undefined>,
  'submitQuoteRequest' : ActorMethod<[QuoteRequestArgs], bigint>,
  'updateOrderStatus' : ActorMethod<[OrderUpdateArgs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];