/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerProfile = IDL.Record({
  'contactName' : IDL.Text,
  'gstNumber' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const QuoteRequest = IDL.Record({
  'id' : IDL.Nat,
  'height' : IDL.Float64,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'drawingFileId' : IDL.Opt(IDL.Text),
  'deliveryLocation' : IDL.Text,
  'boxType' : IDL.Text,
  'length' : IDL.Float64,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Principal,
  'width' : IDL.Float64,
  'adminNotes' : IDL.Opt(IDL.Text),
  'material' : IDL.Text,
});
export const GetEmailUserProfileArgs = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const GetEmailUserProfileResult = IDL.Variant({
  'ok' : CustomerProfile,
  'errWrongPassword' : IDL.Text,
  'errNotFound' : IDL.Text,
});
export const Quotation = IDL.Record({
  'deliveryCharge' : IDL.Float64,
  'requestId' : IDL.Nat,
  'gstPercent' : IDL.Float64,
  'sentAt' : IDL.Int,
  'notes' : IDL.Opt(IDL.Text),
  'totalPrice' : IDL.Float64,
  'basePrice' : IDL.Float64,
  'validUntil' : IDL.Int,
});
export const InvoiceData = IDL.Record({
  'customer' : CustomerProfile,
  'request' : QuoteRequest,
  'quotation' : Quotation,
});
export const Order = IDL.Record({
  'requestId' : IDL.Nat,
  'manufacturingNotes' : IDL.Opt(IDL.Text),
  'deliveryTrackingInfo' : IDL.Opt(IDL.Text),
  'finalPaid' : IDL.Bool,
  'advancePaid' : IDL.Bool,
  'customerId' : IDL.Principal,
});
export const LoginEmailUserArgs = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const LoginEmailUserResult = IDL.Variant({
  'ok' : CustomerProfile,
  'errWrongPassword' : IDL.Text,
  'errNotFound' : IDL.Text,
});
export const RegisterCustomerProfileArgs = IDL.Record({
  'contactName' : IDL.Text,
  'gstNumber' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const RegisterEmailUserArgs = IDL.Record({
  'contactName' : IDL.Text,
  'gstNumber' : IDL.Text,
  'password' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const RegisterEmailUserResult = IDL.Variant({
  'ok' : IDL.Null,
  'errInvalid' : IDL.Text,
  'errEmailTaken' : IDL.Text,
});
export const QuotationArgs = IDL.Record({
  'deliveryCharge' : IDL.Float64,
  'requestId' : IDL.Nat,
  'gstPercent' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'basePrice' : IDL.Float64,
  'validUntil' : IDL.Int,
});
export const QuoteRequestArgs = IDL.Record({
  'height' : IDL.Float64,
  'drawingFileId' : IDL.Opt(IDL.Text),
  'deliveryLocation' : IDL.Text,
  'boxType' : IDL.Text,
  'length' : IDL.Float64,
  'quantity' : IDL.Nat,
  'width' : IDL.Float64,
  'material' : IDL.Text,
});
export const EmailProfileUpdateArgs = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
  'profile' : CustomerProfile,
});
export const UpdateEmailUserProfileResult = IDL.Variant({
  'ok' : IDL.Null,
  'errWrongPassword' : IDL.Text,
  'errNotFound' : IDL.Text,
});
export const OrderUpdateArgs = IDL.Record({
  'requestId' : IDL.Nat,
  'manufacturingNotes' : IDL.Opt(IDL.Text),
  'deliveryTrackingInfo' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveQuote' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCustomers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CustomerProfile))],
      ['query'],
    ),
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmailUserProfile' : IDL.Func(
      [GetEmailUserProfileArgs],
      [GetEmailUserProfileResult],
      [],
    ),
  'getInvoiceData' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceData)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getMyQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getQuotation' : IDL.Func([IDL.Nat], [IDL.Opt(Quotation)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginEmailUser' : IDL.Func([LoginEmailUserArgs], [LoginEmailUserResult], []),
  'markAdvancePaid' : IDL.Func([IDL.Nat], [], []),
  'registerCustomerProfile' : IDL.Func([RegisterCustomerProfileArgs], [], []),
  'registerEmailUser' : IDL.Func(
      [RegisterEmailUserArgs],
      [RegisterEmailUserResult],
      [],
    ),
  'rejectQuote' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
  'sendQuotation' : IDL.Func([QuotationArgs], [], []),
  'submitQuoteRequest' : IDL.Func([QuoteRequestArgs], [IDL.Nat], []),
  'updateEmailUserProfile' : IDL.Func(
      [EmailProfileUpdateArgs],
      [UpdateEmailUserProfileResult],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderUpdateArgs], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerProfile = IDL.Record({
    'contactName' : IDL.Text,
    'gstNumber' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const QuoteRequest = IDL.Record({
    'id' : IDL.Nat,
    'height' : IDL.Float64,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'drawingFileId' : IDL.Opt(IDL.Text),
    'deliveryLocation' : IDL.Text,
    'boxType' : IDL.Text,
    'length' : IDL.Float64,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Principal,
    'width' : IDL.Float64,
    'adminNotes' : IDL.Opt(IDL.Text),
    'material' : IDL.Text,
  });
  const GetEmailUserProfileArgs = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const GetEmailUserProfileResult = IDL.Variant({
    'ok' : CustomerProfile,
    'errWrongPassword' : IDL.Text,
    'errNotFound' : IDL.Text,
  });
  const Quotation = IDL.Record({
    'deliveryCharge' : IDL.Float64,
    'requestId' : IDL.Nat,
    'gstPercent' : IDL.Float64,
    'sentAt' : IDL.Int,
    'notes' : IDL.Opt(IDL.Text),
    'totalPrice' : IDL.Float64,
    'basePrice' : IDL.Float64,
    'validUntil' : IDL.Int,
  });
  const InvoiceData = IDL.Record({
    'customer' : CustomerProfile,
    'request' : QuoteRequest,
    'quotation' : Quotation,
  });
  const Order = IDL.Record({
    'requestId' : IDL.Nat,
    'manufacturingNotes' : IDL.Opt(IDL.Text),
    'deliveryTrackingInfo' : IDL.Opt(IDL.Text),
    'finalPaid' : IDL.Bool,
    'advancePaid' : IDL.Bool,
    'customerId' : IDL.Principal,
  });
  const LoginEmailUserArgs = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const LoginEmailUserResult = IDL.Variant({
    'ok' : CustomerProfile,
    'errWrongPassword' : IDL.Text,
    'errNotFound' : IDL.Text,
  });
  const RegisterCustomerProfileArgs = IDL.Record({
    'contactName' : IDL.Text,
    'gstNumber' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RegisterEmailUserArgs = IDL.Record({
    'contactName' : IDL.Text,
    'gstNumber' : IDL.Text,
    'password' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RegisterEmailUserResult = IDL.Variant({
    'ok' : IDL.Null,
    'errInvalid' : IDL.Text,
    'errEmailTaken' : IDL.Text,
  });
  const QuotationArgs = IDL.Record({
    'deliveryCharge' : IDL.Float64,
    'requestId' : IDL.Nat,
    'gstPercent' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'basePrice' : IDL.Float64,
    'validUntil' : IDL.Int,
  });
  const QuoteRequestArgs = IDL.Record({
    'height' : IDL.Float64,
    'drawingFileId' : IDL.Opt(IDL.Text),
    'deliveryLocation' : IDL.Text,
    'boxType' : IDL.Text,
    'length' : IDL.Float64,
    'quantity' : IDL.Nat,
    'width' : IDL.Float64,
    'material' : IDL.Text,
  });
  const EmailProfileUpdateArgs = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
    'profile' : CustomerProfile,
  });
  const UpdateEmailUserProfileResult = IDL.Variant({
    'ok' : IDL.Null,
    'errWrongPassword' : IDL.Text,
    'errNotFound' : IDL.Text,
  });
  const OrderUpdateArgs = IDL.Record({
    'requestId' : IDL.Nat,
    'manufacturingNotes' : IDL.Opt(IDL.Text),
    'deliveryTrackingInfo' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveQuote' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCustomers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CustomerProfile))],
        ['query'],
      ),
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmailUserProfile' : IDL.Func(
        [GetEmailUserProfileArgs],
        [GetEmailUserProfileResult],
        [],
      ),
    'getInvoiceData' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceData)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
    'getMyQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getQuotation' : IDL.Func([IDL.Nat], [IDL.Opt(Quotation)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginEmailUser' : IDL.Func(
        [LoginEmailUserArgs],
        [LoginEmailUserResult],
        [],
      ),
    'markAdvancePaid' : IDL.Func([IDL.Nat], [], []),
    'registerCustomerProfile' : IDL.Func([RegisterCustomerProfileArgs], [], []),
    'registerEmailUser' : IDL.Func(
        [RegisterEmailUserArgs],
        [RegisterEmailUserResult],
        [],
      ),
    'rejectQuote' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
    'sendQuotation' : IDL.Func([QuotationArgs], [], []),
    'submitQuoteRequest' : IDL.Func([QuoteRequestArgs], [IDL.Nat], []),
    'updateEmailUserProfile' : IDL.Func(
        [EmailProfileUpdateArgs],
        [UpdateEmailUserProfileResult],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderUpdateArgs], [], []),
  });
};

export const init = ({ IDL }) => { return []; };