/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InvoiceData {
    customer: CustomerProfile;
    request: QuoteRequest;
    quotation: Quotation;
}
export interface RegisterCustomerProfileArgs {
    contactName: string;
    gstNumber: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
}
export interface QuoteRequestArgs {
    height: number;
    drawingFileId?: string;
    deliveryLocation: string;
    boxType: string;
    length: number;
    quantity: bigint;
    width: number;
    material: string;
}
export interface QuotationArgs {
    deliveryCharge: number;
    requestId: bigint;
    gstPercent: number;
    notes?: string;
    basePrice: number;
    validUntil: bigint;
}
export interface QuoteRequest {
    id: bigint;
    height: number;
    status: string;
    createdAt: bigint;
    drawingFileId?: string;
    deliveryLocation: string;
    boxType: string;
    length: number;
    quantity: bigint;
    customerId: Principal;
    width: number;
    adminNotes?: string;
    material: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface LoginEmailUserArgs {
    password: string;
    email: string;
}
export type GetEmailUserProfileResult = {
    __kind__: "ok";
    ok: CustomerProfile;
} | {
    __kind__: "errWrongPassword";
    errWrongPassword: string;
} | {
    __kind__: "errNotFound";
    errNotFound: string;
};
export interface GetEmailUserProfileArgs {
    password: string;
    email: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CustomerProfile {
    contactName: string;
    gstNumber: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
}
export interface Order {
    requestId: bigint;
    manufacturingNotes?: string;
    deliveryTrackingInfo?: string;
    finalPaid: boolean;
    advancePaid: boolean;
    customerId: Principal;
}
export interface Quotation {
    deliveryCharge: number;
    requestId: bigint;
    gstPercent: number;
    sentAt: bigint;
    notes?: string;
    totalPrice: number;
    basePrice: number;
    validUntil: bigint;
}
export interface EmailProfileUpdateArgs {
    password: string;
    email: string;
    profile: CustomerProfile;
}
export interface RegisterEmailUserArgs {
    contactName: string;
    gstNumber: string;
    password: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
}
export type LoginEmailUserResult = {
    __kind__: "ok";
    ok: CustomerProfile;
} | {
    __kind__: "errWrongPassword";
    errWrongPassword: string;
} | {
    __kind__: "errNotFound";
    errNotFound: string;
};
export type UpdateEmailUserProfileResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "errWrongPassword";
    errWrongPassword: string;
} | {
    __kind__: "errNotFound";
    errNotFound: string;
};
export type RegisterEmailUserResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "errInvalid";
    errInvalid: string;
} | {
    __kind__: "errEmailTaken";
    errEmailTaken: string;
};
export interface OrderUpdateArgs {
    requestId: bigint;
    manufacturingNotes?: string;
    deliveryTrackingInfo?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveQuote(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllCustomers(): Promise<Array<[Principal, CustomerProfile]>>;
    getAllQuoteRequests(): Promise<Array<QuoteRequest>>;
    getCallerUserProfile(): Promise<CustomerProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmailUserProfile(args: GetEmailUserProfileArgs): Promise<GetEmailUserProfileResult>;
    getInvoiceData(requestId: bigint): Promise<InvoiceData | null>;
    getMyProfile(): Promise<CustomerProfile | null>;
    getMyQuoteRequests(): Promise<Array<QuoteRequest>>;
    getOrder(requestId: bigint): Promise<Order | null>;
    getQuotation(requestId: bigint): Promise<Quotation | null>;
    getUserProfile(user: Principal): Promise<CustomerProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginEmailUser(args: LoginEmailUserArgs): Promise<LoginEmailUserResult>;
    markAdvancePaid(requestId: bigint): Promise<void>;
    registerCustomerProfile(args: RegisterCustomerProfileArgs): Promise<void>;
    registerEmailUser(args: RegisterEmailUserArgs): Promise<RegisterEmailUserResult>;
    rejectQuote(requestId: bigint): Promise<void>;
    saveCallerUserProfile(profile: CustomerProfile): Promise<void>;
    sendQuotation(args: QuotationArgs): Promise<void>;
    submitQuoteRequest(args: QuoteRequestArgs): Promise<bigint>;
    updateEmailUserProfile(args: EmailProfileUpdateArgs): Promise<UpdateEmailUserProfileResult>;
    updateOrderStatus(args: OrderUpdateArgs): Promise<void>;
}
import type { CustomerProfile as _CustomerProfile, GetEmailUserProfileResult as _GetEmailUserProfileResult, InvoiceData as _InvoiceData, LoginEmailUserResult as _LoginEmailUserResult, Order as _Order, OrderUpdateArgs as _OrderUpdateArgs, Quotation as _Quotation, QuotationArgs as _QuotationArgs, QuoteRequest as _QuoteRequest, QuoteRequestArgs as _QuoteRequestArgs, RegisterEmailUserResult as _RegisterEmailUserResult, UpdateEmailUserProfileResult as _UpdateEmailUserProfileResult, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveQuote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveQuote(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<[Principal, CustomerProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllQuoteRequests(): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuoteRequests();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuoteRequests();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmailUserProfile(arg0: GetEmailUserProfileArgs): Promise<GetEmailUserProfileResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailUserProfile(arg0);
                return from_candid_GetEmailUserProfileResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailUserProfile(arg0);
            return from_candid_GetEmailUserProfileResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceData(arg0: bigint): Promise<InvoiceData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceData(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceData(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQuoteRequests(): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuoteRequests();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuoteRequests();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotation(arg0: bigint): Promise<Quotation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotation(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotation(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginEmailUser(arg0: LoginEmailUserArgs): Promise<LoginEmailUserResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginEmailUser(arg0);
                return from_candid_LoginEmailUserResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginEmailUser(arg0);
            return from_candid_LoginEmailUserResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAdvancePaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAdvancePaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAdvancePaid(arg0);
            return result;
        }
    }
    async registerCustomerProfile(arg0: RegisterCustomerProfileArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomerProfile(arg0);
            return result;
        }
    }
    async registerEmailUser(arg0: RegisterEmailUserArgs): Promise<RegisterEmailUserResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerEmailUser(arg0);
                return from_candid_RegisterEmailUserResult_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerEmailUser(arg0);
            return from_candid_RegisterEmailUserResult_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectQuote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectQuote(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: CustomerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendQuotation(arg0: QuotationArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendQuotation(to_candid_QuotationArgs_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendQuotation(to_candid_QuotationArgs_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitQuoteRequest(arg0: QuoteRequestArgs): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuoteRequest(to_candid_QuoteRequestArgs_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuoteRequest(to_candid_QuoteRequestArgs_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmailUserProfile(arg0: EmailProfileUpdateArgs): Promise<UpdateEmailUserProfileResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmailUserProfile(arg0);
                return from_candid_UpdateEmailUserProfileResult_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmailUserProfile(arg0);
            return from_candid_UpdateEmailUserProfileResult_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderUpdateArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(to_candid_OrderUpdateArgs_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(to_candid_OrderUpdateArgs_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_GetEmailUserProfileResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GetEmailUserProfileResult): GetEmailUserProfileResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceData_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceData): InvoiceData {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_LoginEmailUserResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginEmailUserResult): LoginEmailUserResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Quotation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quotation): Quotation {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteRequest): QuoteRequest {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterEmailUserResult_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterEmailUserResult): RegisterEmailUserResult {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateEmailUserProfileResult_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateEmailUserProfileResult): UpdateEmailUserProfileResult {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceData]): InvoiceData | null {
    return value.length === 0 ? null : from_candid_InvoiceData_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quotation]): Quotation | null {
    return value.length === 0 ? null : from_candid_Quotation_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    height: number;
    status: string;
    createdAt: bigint;
    drawingFileId: [] | [string];
    deliveryLocation: string;
    boxType: string;
    length: number;
    quantity: bigint;
    customerId: Principal;
    width: number;
    adminNotes: [] | [string];
    material: string;
}): {
    id: bigint;
    height: number;
    status: string;
    createdAt: bigint;
    drawingFileId?: string;
    deliveryLocation: string;
    boxType: string;
    length: number;
    quantity: bigint;
    customerId: Principal;
    width: number;
    adminNotes?: string;
    material: string;
} {
    return {
        id: value.id,
        height: value.height,
        status: value.status,
        createdAt: value.createdAt,
        drawingFileId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.drawingFileId)),
        deliveryLocation: value.deliveryLocation,
        boxType: value.boxType,
        length: value.length,
        quantity: value.quantity,
        customerId: value.customerId,
        width: value.width,
        adminNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.adminNotes)),
        material: value.material
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: _CustomerProfile;
    request: _QuoteRequest;
    quotation: _Quotation;
}): {
    customer: CustomerProfile;
    request: QuoteRequest;
    quotation: Quotation;
} {
    return {
        customer: value.customer,
        request: from_candid_QuoteRequest_n11(_uploadFile, _downloadFile, value.request),
        quotation: from_candid_Quotation_n22(_uploadFile, _downloadFile, value.quotation)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveryCharge: number;
    requestId: bigint;
    gstPercent: number;
    sentAt: bigint;
    notes: [] | [string];
    totalPrice: number;
    basePrice: number;
    validUntil: bigint;
}): {
    deliveryCharge: number;
    requestId: bigint;
    gstPercent: number;
    sentAt: bigint;
    notes?: string;
    totalPrice: number;
    basePrice: number;
    validUntil: bigint;
} {
    return {
        deliveryCharge: value.deliveryCharge,
        requestId: value.requestId,
        gstPercent: value.gstPercent,
        sentAt: value.sentAt,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes)),
        totalPrice: value.totalPrice,
        basePrice: value.basePrice,
        validUntil: value.validUntil
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requestId: bigint;
    manufacturingNotes: [] | [string];
    deliveryTrackingInfo: [] | [string];
    finalPaid: boolean;
    advancePaid: boolean;
    customerId: Principal;
}): {
    requestId: bigint;
    manufacturingNotes?: string;
    deliveryTrackingInfo?: string;
    finalPaid: boolean;
    advancePaid: boolean;
    customerId: Principal;
} {
    return {
        requestId: value.requestId,
        manufacturingNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.manufacturingNotes)),
        deliveryTrackingInfo: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.deliveryTrackingInfo)),
        finalPaid: value.finalPaid,
        advancePaid: value.advancePaid,
        customerId: value.customerId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CustomerProfile;
} | {
    errWrongPassword: string;
} | {
    errNotFound: string;
}): {
    __kind__: "ok";
    ok: CustomerProfile;
} | {
    __kind__: "errWrongPassword";
    errWrongPassword: string;
} | {
    __kind__: "errNotFound";
    errNotFound: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "errWrongPassword" in value ? {
        __kind__: "errWrongPassword",
        errWrongPassword: value.errWrongPassword
    } : "errNotFound" in value ? {
        __kind__: "errNotFound",
        errNotFound: value.errNotFound
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    errInvalid: string;
} | {
    errEmailTaken: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "errInvalid";
    errInvalid: string;
} | {
    __kind__: "errEmailTaken";
    errEmailTaken: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "errInvalid" in value ? {
        __kind__: "errInvalid",
        errInvalid: value.errInvalid
    } : "errEmailTaken" in value ? {
        __kind__: "errEmailTaken",
        errEmailTaken: value.errEmailTaken
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    errWrongPassword: string;
} | {
    errNotFound: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "errWrongPassword";
    errWrongPassword: string;
} | {
    __kind__: "errNotFound";
    errNotFound: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "errWrongPassword" in value ? {
        __kind__: "errWrongPassword",
        errWrongPassword: value.errWrongPassword
    } : "errNotFound" in value ? {
        __kind__: "errNotFound",
        errNotFound: value.errNotFound
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuoteRequest>): Array<QuoteRequest> {
    return value.map((x)=>from_candid_QuoteRequest_n11(_uploadFile, _downloadFile, x));
}
function to_candid_OrderUpdateArgs_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderUpdateArgs): _OrderUpdateArgs {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_QuotationArgs_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationArgs): _QuotationArgs {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_QuoteRequestArgs_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteRequestArgs): _QuoteRequestArgs {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveryCharge: number;
    requestId: bigint;
    gstPercent: number;
    notes?: string;
    basePrice: number;
    validUntil: bigint;
}): {
    deliveryCharge: number;
    requestId: bigint;
    gstPercent: number;
    notes: [] | [string];
    basePrice: number;
    validUntil: bigint;
} {
    return {
        deliveryCharge: value.deliveryCharge,
        requestId: value.requestId,
        gstPercent: value.gstPercent,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        basePrice: value.basePrice,
        validUntil: value.validUntil
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    height: number;
    drawingFileId?: string;
    deliveryLocation: string;
    boxType: string;
    length: number;
    quantity: bigint;
    width: number;
    material: string;
}): {
    height: number;
    drawingFileId: [] | [string];
    deliveryLocation: string;
    boxType: string;
    length: number;
    quantity: bigint;
    width: number;
    material: string;
} {
    return {
        height: value.height,
        drawingFileId: value.drawingFileId ? candid_some(value.drawingFileId) : candid_none(),
        deliveryLocation: value.deliveryLocation,
        boxType: value.boxType,
        length: value.length,
        quantity: value.quantity,
        width: value.width,
        material: value.material
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requestId: bigint;
    manufacturingNotes?: string;
    deliveryTrackingInfo?: string;
}): {
    requestId: bigint;
    manufacturingNotes: [] | [string];
    deliveryTrackingInfo: [] | [string];
} {
    return {
        requestId: value.requestId,
        manufacturingNotes: value.manufacturingNotes ? candid_some(value.manufacturingNotes) : candid_none(),
        deliveryTrackingInfo: value.deliveryTrackingInfo ? candid_some(value.deliveryTrackingInfo) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
